export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_REGISTER_SUCCESS = 'GET_REGISTER_SUCCESS';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
